name: Tests

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          pip3 install pre-commit
          pre-commit run --origin HEAD --source origin/HEAD
