name: Tests

on: [pull_request]

jobs:
  Linting:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
          source "${HOME}/.poetry/env"
      - name: Linting
        run: poetry run invoke lint-ci

  Testing:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: tools/ci/install_poetry.sh
      - name: Run Tests
        run: poetry run invoke test
